import { Inter } from "next/font/google";
import StoreProvider from "@/lib/StoreProvider";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Leverage Trading",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <div>
            <Header />
            <Toaster />
            {children}  
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
